package com.coderedrobotics.virtualrobot;

import javax.swing.JFileChooser;

/**
 *
 * @author Michael
 */
public class GUI extends javax.swing.JPanel {

    CodeLoader codeLoader;

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
        codeLoader = new CodeLoader();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        disableButton = new javax.swing.JButton();
        enableButton = new javax.swing.JButton();
        periodSelector = new javax.swing.JComboBox();
        infoLabel = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        loadButton = new javax.swing.JButton();
        iterativeRobotPathField = new javax.swing.JTextField();
        jarPathField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        selectFileButton = new javax.swing.JButton();
        loadButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(51, 51, 51));

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));

        disableButton.setBackground(new java.awt.Color(102, 102, 102));
        disableButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        disableButton.setForeground(new java.awt.Color(255, 0, 0));
        disableButton.setText("DISABLE");
        disableButton.setEnabled(false);
        disableButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                disableButtonActionPerformed(evt);
            }
        });

        enableButton.setBackground(new java.awt.Color(102, 102, 102));
        enableButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        enableButton.setForeground(new java.awt.Color(0, 132, 0));
        enableButton.setText("ENABLE");
        enableButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enableButtonActionPerformed(evt);
            }
        });

        periodSelector.setBackground(new java.awt.Color(51, 51, 51));
        periodSelector.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "TeleOperated", "Autonomous", "Test" }));
        periodSelector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                periodSelectorActionPerformed(evt);
            }
        });

        infoLabel.setForeground(new java.awt.Color(255, 255, 255));
        infoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        infoLabel.setText("<html> <center><h3>How to use Virtual Robot</h3></center> <ol> <li>Write some robot code!</li> <li>Change \"extends IterativeRobot\" to \"implements VirtualRobot\"</li> <li>Verify that you have enabled Virtualization in the VirtualizationController</li> <li>Fill in the Path to Jar and path to VirtualRobot fields with absolute paths.</li> <li>Use the virtual Driver Station to the left to enable/disable different periods.</li> </ol> </html>");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(periodSelector, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(enableButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(disableButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(infoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 473, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(periodSelector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(enableButton, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                            .addComponent(disableButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(infoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel7.setBackground(new java.awt.Color(102, 102, 102));

        loadButton.setBackground(new java.awt.Color(102, 102, 102));
        loadButton.setText("LOAD");
        loadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadButtonActionPerformed(evt);
            }
        });

        iterativeRobotPathField.setToolTipText("");
        iterativeRobotPathField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iterativeRobotPathFieldActionPerformed(evt);
            }
        });

        jarPathField.setToolTipText("");
        jarPathField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jarPathFieldActionPerformed(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Path to JAR:");

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Path to VirtualRobot:");

        selectFileButton.setBackground(new java.awt.Color(102, 102, 102));
        selectFileButton.setText("Browse...");
        selectFileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectFileButtonActionPerformed(evt);
            }
        });

        loadButton1.setBackground(new java.awt.Color(102, 102, 102));
        loadButton1.setText("UNLOAD");
        loadButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(iterativeRobotPathField, javax.swing.GroupLayout.DEFAULT_SIZE, 368, Short.MAX_VALUE)
                    .addComponent(jarPathField))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(selectFileButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(loadButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(loadButton, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jarPathField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selectFileButton)
                    .addComponent(loadButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(iterativeRobotPathField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(loadButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void loadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadButtonActionPerformed
        codeLoader.loadCode(jarPathField.getText(), iterativeRobotPathField.getText());
        codeLoader.disable();
    }//GEN-LAST:event_loadButtonActionPerformed

    private void iterativeRobotPathFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iterativeRobotPathFieldActionPerformed
        codeLoader.loadCode(jarPathField.getText(), iterativeRobotPathField.getText());
        codeLoader.disable();
    }//GEN-LAST:event_iterativeRobotPathFieldActionPerformed

    private void jarPathFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jarPathFieldActionPerformed
        codeLoader.loadCode(jarPathField.getText(), iterativeRobotPathField.getText());
        codeLoader.disable();
    }//GEN-LAST:event_jarPathFieldActionPerformed

    private void enableButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enableButtonActionPerformed
        codeLoader.enable();
        disableButton.setEnabled(true);
        enableButton.setEnabled(false);
    }//GEN-LAST:event_enableButtonActionPerformed

    private void disableButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_disableButtonActionPerformed
        codeLoader.disable();
        enableButton.setEnabled(true);
        disableButton.setEnabled(false);
    }//GEN-LAST:event_disableButtonActionPerformed

    private void periodSelectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_periodSelectorActionPerformed
        switch(periodSelector.getSelectedIndex()) {
            case 0:
                codeLoader.setMode(CodeLoader.MODE.TELEOP);
                break;
            case 1:
                codeLoader.setMode(CodeLoader.MODE.AUTON);
                break;
            case 2:
                codeLoader.setMode(CodeLoader.MODE.TEST);
                break;
        }
    }//GEN-LAST:event_periodSelectorActionPerformed

    private void selectFileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectFileButtonActionPerformed
        JFileChooser fc = new JFileChooser();
        int returnVal = fc.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            jarPathField.setText(fc.getSelectedFile().getAbsolutePath());
        }
    }//GEN-LAST:event_selectFileButtonActionPerformed

    private void loadButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadButton1ActionPerformed
        codeLoader.unloadCode();
    }//GEN-LAST:event_loadButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton disableButton;
    private javax.swing.JButton enableButton;
    private javax.swing.JLabel infoLabel;
    private javax.swing.JTextField iterativeRobotPathField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JTextField jarPathField;
    private javax.swing.JButton loadButton;
    private javax.swing.JButton loadButton1;
    private javax.swing.JComboBox periodSelector;
    private javax.swing.JButton selectFileButton;
    // End of variables declaration//GEN-END:variables

}
